### ISSUE TITLE
Dealing With Conflicting Links #12 

### ISSUE THREAD

**Issue by keyphact** [pogodevorg/awesome-pokemongo#13]
As discussed in: #12 , please come up with a way to deal with links or projects that are conflicting with each other, either for source code, or their names.

Do we allow users to remove the links?
Do the project maintainers remove the links?
Do we keep both?

**Comment by prusswan** [comment]
From what I can tell, one of the projects is effectively a fork of the other, even though the respective owners cannot agree on the licensing. So perhaps both projects can be listed, with the disclaimer that listing has no bearing on licensing disputes and cannot serve as any form of endorsement.

**Comment by jekirl** [comment]
The background:
He downloaded my repo, deleted the .git history, and removed the license/copyleft requirement. When he got called out he added the license, but then ended up deleting the git history again and disabling issues/pull requests. 

Regardless of what happened though, the questions you asked are valid and I am not sure what the right answer is. I am interested to hear what others think...

**Comment by zeevallin** [comment]
When we see conflicting projects I'd say if it was added at the point of which the license was a proper open source license we keep the link to both providing they both have a license. If there is a dispute without license, I'd recommend removing the links. If that makes sense. Thoughts?

**Comment by zeevallin** [comment]
On this topic, I've opened a ticket for POGOProtos regarding license seeing as most implementation projects use their code. https://github.com/AeonLucid/POGOProtos/issues/67

**Comment by keyphact** [comment]
Looking at everyone's comments, I'm of a similar mind that if the projects are open sourced then we will list both regardless of the disputes on licensing.

When we have conflicting interests on closed sources then we'll remove both and let the project co-ordinators come to an open agreement on a public open pull request.

How does that sound?

**Comment by zeevallin** [comment]
Sounds good to me.

**Comment by keyphact** [comment]
Great, we'll deal with future conflicts in this manner, closing off for now.

If anyone else has anything else to add or feels it should be re-opened, feel free to comment along with your reasons why it should be revisited. 

Thanks
