### ISSUE TITLE
Pogo hashing

### ISSUE THREAD

**Issue by zarEclEC** [pogodevorg/awesome-pokemongo#70]
Can someone explain something I don't understand?
Why an official app (Pokémon GO from Google Play Store) and a unofficial one are different?
Why do we need to pay for hashing services? Can't we just re-create what happens in the official app? Why with the official app there is no need to pay hashing services?

**Comment by rafalwrzeszcz** [comment]
https://talk.pogodev.org/d/55-api-hashing-service-f-a-q

**Comment by zarEclEC** [comment]
So basically developers aren't doing this for free anymore?
Just to know, has Niantic changed APIs again after their great idea on making users pay?
If no, why don't they return to include those hashing function into the opensource code?
If original Pokémon GO doesn't need any hashing service, why should opensource apps need any?

**Comment by rafalwrzeszcz** [comment]
Please just read again the link. If still unsure - just read again once again.

**Comment by zarEclEC** [comment]
I've read it. Just please explain to me what I don't understand

**Comment by zarEclEC** [comment]
Before closing, could someone gently answer me?
